//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MazeEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MazeEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;Hokuyo&quot;:	{
        ///		&quot;Angles&quot;:	[0, 0, 0, 51533562114, 0, 0, 0, 7.314556e+221, 0, 0],
        ///		&quot;Distances&quot;:	[444, 134960104, 134957472, 3, 1, -1208229404, -1208229404, -1208229404, 0, 5]
        ///	},
        ///	&quot;Particles&quot;:	[{
        ///			&quot;X&quot;:	0,
        ///			&quot;Y&quot;:	0,
        ///			&quot;P&quot;:	0,
        ///			&quot;Angle&quot;:	4.920358,
        ///			&quot;CalculatedProbability&quot;:	[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2.389508e+180, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        ///			&quot;CalculatedDistances&quot;:	[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6.323005e+233, 0, 0, 0, 0, 5.951394e+228, 7.204866e+252, 3.277358e+180, 9.083672e+223, 0]
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonTest {
            get {
                return ResourceManager.GetString("JsonTest", resourceCulture);
            }
        }
    }
}
